# Generated by Django 3.2.15 on 2023-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
